move to more standardized template

diff --git a/bin/list-all b/bin/list-all
--- a/bin/list-all
+++ b/bin/list-all
@@ -1,6 +1,7 @@
 #!/usr/bin/env bash
 set -Eeuo pipefail
 
+TOOL_NAME="kube-release"
 DEBUG="${DEBUG:-}"
 GITHUB_API_TOKEN="${GITHUB_API_TOKEN:-}"
 
@@ -15,10 +16,8 @@ fail() {
 
 curl_opts=(-fsSL)
 releases_path=https://api.github.com/repos/kubernetes/kubernetes/releases
-curl_cmd="$(command -vp curl)"
-cmd="${curl_cmd} -fsS"
 if [ -n "$GITHUB_API_TOKEN" ]; then
-  cmd="$cmd -H 'Authorization: token $GITHUB_API_TOKEN'"
+  curl_opts=("${curl_opts[@]}" -H "Authorization: token $GITHUB_API_TOKEN")
 fi
 
 # stolen from https://github.com/rbenv/ruby-build/pull/631/files#diff-fdcfb8a18714b33b07529b7d02b54f1dR942
@@ -28,11 +27,11 @@ sort_versions() {
 }
 
 # Fetch all tag names, and get only second column. Then remove all unnecesary characters.
-raw_versions="$(eval $cmd $releases_path)"
+raw_versions="$(curl "${curl_opts[@]}" "$releases_path" || fail "Could not download $releases_path")"
 greped_versions=$(echo "${raw_versions}" | grep -oE "tag_name\": *\".{1,15}\",")
 unsorted_versions=$(echo "${greped_versions}" | sed 's/tag_name\": *\"v//;s/\",//')
 versions=$(echo "$unsorted_versions" | sort_versions)
-stable_version="$($cmd https://storage.googleapis.com/kubernetes-release/release/stable.txt | tr -d v)"
+stable_version="$(curl https://storage.googleapis.com/kubernetes-release/release/stable.txt | tr -d v)"
 printf "stable(${stable_version}) "
 echo $versions
 
